Module7 task1
htmlacademy-javascript/89187-keksobooking-23 pull request #5
Opened 2021-07-01 10:07 UTC by paulhardwork

2021-07-01 10:31 UTC, ademaro commented on index.html
> +            <option value="hotel">Оте0ль</option>
0 — убрать)

2021-07-01 10:32 UTC, ademaro commented on js/adverts.js
> +};
генерацию объектов предлагаю перенести в main.js

2021-07-01 10:33 UTC, ademaro commented on js/adverts.js
> +};
я про сам вызов функции getAdvertsList(), определение — в data.js

2021-07-01 10:34 UTC, ademaro commented on js/adverts.js
> +similarAdverts.forEach((advert) => {
нам нужна отдельная функция генерации карточки, одной карточки, а не всего массива, если что

2021-07-01 10:35 UTC, ademaro requested changes
В целом — норм, молодец, но нужно немного доделать, что бы двинуть дальше. ПР оставляю открытым. Если нужна помощь — пиши или набирай, разберём подробнее

2021-07-02 12:38 UTC, ademaro commented on js/adverts.js
> +similarAdverts.forEach((advert) => {
одной карточки!!

2021-07-02 12:44 UTC, ademaro approved these changes
В целом уже подготовили норм код для следующих этапов, круто! Двигаем дальше, по возможности улучшаем код.

2021-07-02 12:44 UTC, ademaro commented on js/adverts.js
> +const getNewAdvert = function (advert) {
тут мы больше рендрим DOM, а не генерим данные, можешь, что бы меньше путаться поменять везде get на generate где генерим ДАННЫЕ, и render — где формируем разметку. Так чуть понятнее будет, думаю

2021-07-02 12:44 UTC, ademaro commented on js/adverts.js
> +      photosContainer.insertAdjacentHTML('beforeend', '<img src="" class="popup__photo" width="40" height="40" alt="Фотография отеля">');
у тебя есть шаблон для тега, давай его клонировать, а не удалять и делать из строки

2021-07-02 12:44 UTC, ademaro commented on js/adverts.js
> +    if ((advertFields[index].textContent === '' && advertFields[index].innerHTML === '' &&  advertFields[index].tagName !== 'IMG') || (advertFields[index].src === '' && advertFields[index].tagName ==
это постобработка, желательно всё делать во время того, как вставляешь данные. За то, что реализовал скрытие — плюс, за не оптимальность — надо подумать как лучше))

2021-07-02 12:44 UTC, ademaro commented on js/data.js
> +  const locationLat = getRandomNumber(Location.LOWER_LAT, Location.UPPER_LAT, 5);
5 — так же в константу

2021-07-02 12:45 UTC, merged

2021-07-02 12:49 UTC, paulhardwork commented on js/adverts.js
> +    if ((advertFields[index].textContent === '' && advertFields[index].innerHTML === '' &&  advertFields[index].tagName !== 'IMG') || (advertFields[index].src === '' && advertFields[index].tagName ==
Ну если для каждого элемента будет вызываться функция проверки, так же точно будет хуже? Подумаю в любом случае.

2021-07-02 12:50 UTC, paulhardwork commented on js/adverts.js
> +      photosContainer.insertAdjacentHTML('beforeend', '<img src="" class="popup__photo" width="40" height="40" alt="Фотография отеля">');
Согласен, тут поторопился в лоб сделать

2021-07-02 12:52 UTC, ademaro commented on js/adverts.js
> +    if ((advertFields[index].textContent === '' && advertFields[index].innerHTML === '' &&  advertFields[index].tagName !== 'IMG') || (advertFields[index].src === '' && advertFields[index].tagName ==
Так у тебя в цикле и так по сути проверка для каждого элемента)